/**
 * The bundled corridor data and the two constants that belong with it.
 *
 * Kept separate from `src/map/gage-layer.ts` on purpose: the state store and the crossing check need
 * the corridors without importing MapLibre, and the map layer needs them without importing the rule.
 * The artifact itself is generated by `pnpm build:gage` (see `tools/build-gage-polygons.ts`); this
 * module only gives it a type and a single import site.
 */
import artifact from '../data/gage-polygons.json';
import type { CorridorPolygons } from './gage-geometry';

/** The 25 named corridors with their buffered rings, as generated from the source GeoJSON. */
export const CORRIDORS: CorridorPolygons[] = (artifact as unknown as { corridors: CorridorPolygons[] }).corridors;

/** Buffer half-width the source data declares for every road corridor, in metres. */
export const BUFFER_METERS: number = (artifact as unknown as { bufferMeters: number }).bufferMeters;

/** Ring-perimeter ceiling one request may carry; mirrors Valhalla's service limit with a margin. */
export const REQUEST_PERIMETER_BUDGET_METERS: number =
  (artifact as unknown as { requestPerimeterBudgetMeters: number }).requestPerimeterBudgetMeters;
