/**
 * Generate `src/data/gage-polygons.json` from `data/jakarta-ganjil-genap.geojson`.
 *
 * ## What Valhalla's `exclude_polygons` actually accepts (verified, not assumed)
 *
 * Read from the pinned engine's source — Valhalla 3.8.3,
 * [`a60c7cbfc83e073f50887cd27e0109d02e6b64e5`](https://github.com/valhalla/valhalla/tree/a60c7cbfc83e073f50887cd27e0109d02e6b64e5),
 * the revision this app ships as WASM; file references below are relative to that tree — and then
 * confirmed against the live engine by routing this release's Jakarta pair through the WASM runtime
 * with one polygon at a time:
 *
 * - **Container.** `src/worker.cc:1104-1146` reads `/exclude_polygons`; it must be an array or an
 *   object, and anything else gets only warning 204 and is ignored. Each entry is either a ring (a
 *   JSON array) or a GeoJSON feature object, in which case the parser walks
 *   `/geometry/coordinates/0` and requires `/geometry/type == "Polygon"`.
 * - **Coordinate order: `[longitude, latitude]`.** `parse_ring()` (`src/worker.cc:150-186`) states it
 *   in its own comment — "Parses JSON rings of the form [[lon1, lat1], [lon2, lat2], ..." — and then
 *   does `double lon = coords[0].GetDouble(); double lat = coords[1].GetDouble();`, rejecting a
 *   latitude outside ±90 with exception 137. The probe agrees: the same ~400 m Jakarta square
 *   written `[lon, lat]` moved the route from 24.516 km to 15.746 km, while the `[lat, lon]`
 *   encoding threw native 137.
 * - **Point separator: none.** A ring is an array of two-element arrays. The comma-separated
 *   string the earlier spike passed (`"106.8,-6.2 106.9,-6.3"`) is accepted by the type signature
 *   (`exclude_polygons?: string[]`) and then dropped without a word: an entry that is neither an
 *   array nor an object leaves the parser with an *empty* ring (`src/worker.cc:1127-1136`), and
 *   `src/loki/polygon_search.cc:103-105` returns no exclusions when the first ring has no
 *   coordinates. The probe shows it changing nothing at all, which is exactly the "Valhalla accepted
 *   it but nothing happened" trap.
 * - **Ring separator: one array entry per ring**, i.e. `[[[lon,lat],...], [[lon,lat],...]]`.
 * - **Closure: not required.** `edgedist`/`PBFToRing` close an open ring (the API reference says so
 *   explicitly), but every ring this script writes is already closed.
 * - **Total length is capped.** `loki::worker.cc` sums `boost::geometry::perimeter` over every ring
 *   in the request and throws exception 167 (`too_large_polygon`) above
 *   `service_limits.max_exclude_polygons_length` — 10,000 m in this deployment's `config.json`.
 *   Probed: a 12.1 km ring threw native 167 while the identical string form was ignored. This is
 *   why the artifact chunks long corridors and why the request builder packs to a budget.
 *
 * ## Output
 *
 * One entry per named LineString corridor, each with its centre-line and its closed 35 m rings.
 * 25 corridors, 30 rings: five corridors are long enough that one ring would breach the per-ring
 * ceiling below, so they are cut into equal pieces and buffered piece by piece. Deterministic:
 * source feature order, two-space JSON, no timestamps.
 *
 * Usage: `pnpm build:gage` (writes the file) or `pnpm build:gage --check` (fails if it differs).
 *
 * The entry point is TypeScript rather than .mjs so it can import `src/core/gage-geometry` — the same
 * module the app and the unit tests use — with `node --experimental-strip-types` and no bundler. A
 * .mjs entry point cannot carry the type-only imports that core module needs.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  MAX_RING_PERIMETER_METERS,
  REQUEST_PERIMETER_BUDGET_METERS,
  corridorRings,
  type CorridorPolygons,
  type LngLat,
} from '../src/core/gage-geometry.ts';

const SOURCE = join('data', 'jakarta-ganjil-genap.geojson');
const TARGET = join('src', 'data', 'gage-polygons.json');

/** The source `_meta` block, carried through so the artifact names where it came from. */
interface SourceFeature {
  properties: { id: string; name: string; featureType: string; bufferMeters?: number };
  geometry: { type: string; coordinates: LngLat[] | LngLat };
}

const source = JSON.parse(readFileSync(SOURCE, 'utf8')) as { _meta: Record<string, unknown>; features: SourceFeature[] };
const roads = source.features.filter(feature => feature.geometry.type === 'LineString');

const corridors: CorridorPolygons[] = roads.map(feature => {
  const bufferMeters = feature.properties.bufferMeters ?? 35;
  const centerline = feature.geometry.coordinates as LngLat[];
  return {
    id: feature.properties.id,
    name: feature.properties.name,
    bufferMeters,
    centerline,
    rings: corridorRings(centerline, bufferMeters, MAX_RING_PERIMETER_METERS),
  };
});

const artifact = {
  $comment: 'Generated by tools/build-gage-polygons.ts (pnpm build:gage). Do not edit by hand.',
  source: SOURCE,
  sourceMeta: {
    version: source._meta.version,
    builtAt: source._meta.builtAt,
    source: source._meta.source,
    sourceName: source._meta.sourceName,
    activeHours: source._meta.activeHours,
    activeDays: source._meta.activeDays,
    exemptVehicles: source._meta.exemptVehicles,
  },
  bufferMeters: corridors[0]?.bufferMeters ?? 35,
  maxRingPerimeterMeters: MAX_RING_PERIMETER_METERS,
  requestPerimeterBudgetMeters: REQUEST_PERIMETER_BUDGET_METERS,
  corridorCount: corridors.length,
  ringCount: corridors.reduce((total, corridor) => total + corridor.rings.length, 0),
  corridors,
};

// Two-space JSON with a newline: byte-identical between runs, readable in review, and small
// enough (the 25 corridors are ~600 vertices after simplification) to ship inside the bundle.
const encoded = `${JSON.stringify(artifact, null, 2)}\n`;

if (process.argv.includes('--check')) {
  const current = (() => { try { return readFileSync(TARGET, 'utf8'); } catch { return ''; } })();
  if (current !== encoded) {
    console.error(`${TARGET} is stale. Run: pnpm build:gage`);
    process.exit(1);
  }
  console.log(`${TARGET} is up to date (${artifact.ringCount} rings over ${artifact.corridorCount} corridors).`);
} else {
  writeFileSync(TARGET, encoded);
  const longest = corridors.flatMap(corridor => corridor.rings.map(ring => ring.perimeterMeters));
  console.log(`wrote ${TARGET}: ${artifact.ringCount} rings, ${artifact.corridorCount} corridors`);
  console.log(`longest ring ${Math.max(...longest).toFixed(0)} m (ceiling ${MAX_RING_PERIMETER_METERS}), ` +
    `total ${longest.reduce((a, b) => a + b, 0).toFixed(0)} m (request budget ${REQUEST_PERIMETER_BUDGET_METERS})`);
}
